### ISSUE TITLE
Qt-everywhere-opensource-src

### ISSUE THREAD

**Issue by LRonHubs** [Ultimaker/cura-build-environment#38] opened 2018-04-24 15:17 UTC
Someone should submit a pull request replacing the Qt-everywhere-src-5.8.0.tar.xz links with Qt-everywhere-opensource-src-5.8.0.tar.xz, as this is the current link on the server

**Comment by AllenMcAfee** [comment] 2018-04-25 22:27
@LRonHubs I ran into the same issue, but making the mod to the link in qt.cmake seems to not be working on my end.  Running through docker keeps looking for it at http://download.qt.io/official_releases/qt/5.8/5.8.0/single/qt-everywhere-src-5.8.0.tar.xz, rather than http://download.qt.io/official_releases/qt/5.8/5.8.0/single/qt-everywhere-opensource-src-5.8.0.tar.xz.

 Do you have another place your changing this link?  I'm not seeing it anywhere else.

**Comment by thopiekar** [comment] 2018-04-25 23:14
qt.cmake should be the only location.
If it is still using it, then make sure the container is clean or investigate whether something does not revert your changes.
Maybe just commit your changes locally.

Appart from that I sadly can't help more, because I'm using an own copy of cura-vuild-environment, where I changed it and it works. But I'm not using it with Docker.

**Comment by LRonHubs** [comment] 2018-04-26 20:11
Not sure how many links there are. This is the deepest I've had to explore a cmake build, it's possible after some initial building the link is copied into more places. Spoiler: It still doesnt compile on 32-bit linux, even from source

**Comment by thopiekar** [comment] 2018-04-26 20:14
This link should only appear in this file. There should be no reason that there are multiple ones.

About your spoiler: Is this error known? Will soon begin to try to build it on 32bit Linux. In my setup, I rebuild almost every dependency and managed to build for Windows 32bit on 64bit (cross-compiled) and it worked.
However, if that issue is not known here in the tracker, then please add it.

**Comment by AllenMcAfee** [comment] 2018-04-27 06:46
I didn't clean my container as @thopiekar mentioned.  The link is working as expected now.  I can confirm that link in qt.cmake is the only thing that needs fixing for this issue.  Thanks for the help!

**Comment by thopiekar** [comment] 2018-04-27 06:52
No problem. I just guessed that there must be another copy of the file (here in the container itself) laying around somewhere. 😁

**Comment by LRonHubs** [comment] 2018-04-27 12:48
Thanks. I may try the 32-bit linux some more. i just hit a memory error, could be because the computer was doing other stuff

**Comment by thopiekar** [comment] 2018-05-01 15:06
@LipuFei Guess you can close this now. :smile:

**Closed** 2018-05-01 17:03 UTC

**Comment by AllenMcAfee** [comment] 2018-06-25 19:39
@thopiekar @LipuFei Qt 5.8 does not appear to be supported on qt's download page (http://download.qt.io/official_releases/qt/).  Is the plan to move to 5.10 going forward?

**Comment by thopiekar** [comment] 2018-06-26 10:49
Also any changes regarding Python itself?

**Comment by LipuFei** [comment] 2018-06-26 11:06
@thopiekar I managed to upgrade to Python 3.6.5 on Windows and Linux, but the main blocker is compiling Python 3.6.5 on Mac: With all the later OS X, there is System Integrity Protection (SIP), which resets `DYLD_LIBRARY_PATH` to default for any newly spawned processes. The makes it really really hard to compile Python 3.6.5 with option `--enabled-shared`, because it generates `dylib` and the `python` executable depends on it.

We can compile Python 3.6.5 with OS X framework libraries, which is how the official Python 3.6.5 mac os x build does, but I'm not sure if it can still run on older os x due to this dependency.

**Comment by thopiekar** [comment] 2018-06-26 12:03
Months before I faced the same issue here in a VM (which I don't use at the moment because macOS doesn't run inside it very good..)
However, there was a hint how to disable SIP, but don't know how I did it. It was either a command or a setting in the UEFI Bios. But yeah, can't remember that much anymore.

**Comment by LipuFei** [comment] 2018-06-26 12:28
Yes, you can disable SIP in recovery mode (by enabling debugging features), but I don't think you want to do it on a build server...

**Comment by LipuFei** [comment] 2018-06-26 12:30
Besides, even if we disabled SIP on the build machine, when the DMG gets dispatched to end users, we will still run into the same issue. We cannot enforce all users to disable SIP just because they want to run Cura.

**Comment by thopiekar** [comment] 2018-06-26 13:11
Well, before there was no feature like that and nobody had an issue with that. So for the build process I wouldn't care.

I think the idea of SIP is that no binary is allowed to be called outside a application (.app folder) and binaries are not allowed to run third party libraries from another application (.app directory). So I think the final package will be just fine 😬🤞

**Comment by thopiekar** [comment] 2018-06-27 19:30
But yeah, correct me if I'm wrong.
