### ISSUE TITLE
Can't build docker on windows: win1809-python3.8-qt5.15.2-base doesn't exist on docker hub

### ISSUE THREAD

**Issue by eddieparker** [Ultimaker/cura-build-environment#96] opened 2021-05-02 02:05 UTC
Basically what the title says - if you try to build via docker it complains that it can't find that tag.  Looking at docker hub it doesn't seem to exist.

**Comment by Ghostkeeper** [comment] 2021-05-17 09:11
Indeed, the Windows docker image was started as an attempt at some point, but never finished.

Closing this as duplicate of https://github.com/Ultimaker/cura-build-environment/issues/90.

**Closed by Ghostkeeper** 2021-05-17 09:11 UTC
